# Generated by Django 5.0.4 on 2024-06-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0002_fireincident'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FireIncident',
        ),
        migrations.RemoveField(
            model_name='firefighters',
            name='station',
        ),
        migrations.AlterField(
            model_name='firefighters',
            name='rank',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
